### ISSUE TITLE
パネルの「国選択」でCtrlキーを押したままイタリアをクリックしても複数選択されない

### ISSUE THREAD

**Issue by michimaru21167** [mazarimono/python-data-seminar#1]
１１０ページに「パネルの「国選択」で、Ctrlキーを押したままイタリアをクリックしてみましょう」とありますが、日本とイタリアが選択され、コードが水色で選択されるだけで、グラフに折れ線グラフが反映されません。
shiftでの複数の国選択は受け付けているので、マルチセレクトは機能しているものと思われます。
UI的にCtrlを押して国選択が、国選択する前に、コードのセル選択を行う受付になっているようです。
回避方法をご教授願いますでしょうか。

環境
OS：Windows 11 64ビット Pro 22H2
ブラウザ：Chrome 118.0.5993.89（Official Build） （64 ビット）

**Comment by mazarimono** [comment]
反映されない点のご指摘ありがとうございます。

確認して回答させていただきます。
直近、バタバタしておりまして、11月3日までには調査して回答させていただきます。

**Comment by mazarimono** [comment]
Colab環境でも同様の動作になることを確認しました。
執筆時はできてたことなので、対策を調査します。

試してみたこと
```
panelのversionを下げる => X
jupyterlab-widgetsのversionを下げる => X
```

**Comment by mazarimono** [comment]
色々やってみたのですが、結局Colabではおっしゃる通りCtrlがセル選択を行うことに割り当てられていて、複数回クリックすれば選択が反映することが分かったのですが、それ以上に改善する方法が分かりませんでした（申し訳ございません・・）。

執筆時はできたと思っていたのですが、もしかすると当初はローカルの環境（自分のPCで環境作成したJupyter上）で動かしていて、それを動いたと勘違いしてしまっていたのかもしれません。今回もローカルに環境を作成した場合、素直に動いたので、もしよろしければローカルに環境を作ってみて動作確認していただけますと幸いです。

書籍の方は修正機会があれば、修正させていただきます。その機会に向けて、このイシューは残させてください。

間違いをご指摘いただき、誠にありがとうございました。

**Comment by mazarimono** [comment]
あと、修正の際は MultiChoice というウィジェットでColab上で動くものにしようと思っています。次のように、１行の少しを変えるだけで動作するようになりますので、もしよろしければ、こちらも試していただけますと幸いです。

```
# データの読み込み
gapminder = data.gapminder()
# グラフの関数の作成
def make_plot(df, sel_cnt, col):
    df = df[df['country'].isin(sel_cnt)]
    fig = px.line(df, x='year', y=col, color='country', title=f'{col}')
    return fig
# ウィジェットの作成
col_selector = pn.widgets.Select(name='項目選択', options=['lifeExp', 'pop', 'gdpPercap'], value='pop')
cnt_selector = pn.widgets.MultiChoice(name='国選択', options=list(gapminder['country'].unique()), value=['Japan']) # MultiSelect => MultiChoice へ変更
# グラフとウィジェットをバインド
graph = pn.bind(make_plot, gapminder, cnt_selector, col_selector)
# インターフェースの作成
interactive = pn.Column(col_selector, cnt_selector, graph)

interactive
```

![スクリーンショット 2023-11-03 092735](https://github.com/mazarimono/python-data-seminar/assets/32221063/1b9fc44b-812d-46ac-85a8-9e9f42c09ecd)

**Comment by michimaru21167** [comment]
お忙しい中、対応いただきありがとうございました。

私のほうも調べてみました。

Colab環境で[ツール]-[キーボードショートカット]を見るとCtrl + クリックがバインドされており変更もできないようなので、Colab環境ではCtrl + クリックして複数選択するような動作は難しそうです。

ただ、Chrome自体はCtrl + クリックがバインドされていないので、ローカルのJupyteLabでは問題ないように思えます。

MultiChoiceの別案も、動作確認をさせていただき、私の環境でも正常に動作することを確認いたしました。

私もデータを取り扱うお仕事をしており、書籍の内容はとても参考にさせていただいております。

以上、よろしくお願いいたします。

**Comment by mazarimono** [comment]
色々な調査、ご確認ありがとうございます。

書籍の内容がご参考になるようでしたら、筆者としてとてもうれしいです。

書籍の内容でのご質問も大歓迎ですので、遠慮なくお問い合わせください。

今回は動作しない報告ありがとうございました！
